@server = http://localhost:8000
@player_id = 5
@team_id = 2
### 전체 선수 조회
# 프론트의 데이터 확인용, 백이 문서 작성함

GET {{server}}/players

### 특정 선수 조회
GET {{server}}/players/{{player_id}}

### 선수 추가

POST {{server}}/players
Content-Type: application/json; charset=UTF-8

{
    "name" : "손흥민",
    "age" : 30,
    "team_id": 2
}

### 특정 선수의 소속 팀 변경 - 요청 주소에서 1은 player_id를 의미
PATCH {{server}}/players/{{player_id}}/team
Content-Type: application/json; charset=UTF-8

{
    "team_id": 2
}

### 특정 선수 삭제(player_id에 해당하는 Player, Profile 연쇄 삭제)
DELETE {{server}}/players/{{player_id}}

### 전체 팀 조회
GET {{server}}/teams

### 전체 팀 조회 - 이름순으로 오름차순
GET {{server}}/teams?sort=mane_asc

### 전체 팀 조회 - 이름순으로 오름차순
GET {{server}}/teams?search=lg

### 특정 팀 조회
GET {{server}}/teams/{{team_id}}

### 특정 팀의 모든 선수 조회
GET {{server}}/teams/{{team_id}}/players
